jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [test, lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install locust flake8 pytest

      - name: Run unit tests
        if: matrix.task == 'test'
        run: |
          export PYTHONPATH=.
          pytest -v

      - name: Run linter
        if: matrix.task == 'lint'
        run: |
          flake8 .

      - name: Start FastAPI app
        if: matrix.task == 'test'
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5  # wait for the server to start

      - name: Run short load test with Locust
        if: matrix.task == 'test'
        run: |
          locust -f locustfile.p
